# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [4]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

iris_df = load_iris()
iris_df

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
data = iris_df.data
target= iris_df.target

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, test_size= 0.25, random_state= 42)


## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [7]:
from keras.utils import to_categorical

y_train_binary = to_categorical(y_train, num_classes= 3,  dtype= 'int32')
y_train_binary

Using TensorFlow backend.


array([[1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0,

In [8]:
y_test_binary = to_categorical(y_test, num_classes= 3, dtype= 'int32')
y_test_binary

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]], dtype=int32)

In [9]:
print(y_test_binary.shape)
print(y_train_binary.shape)

(38, 3)
(112, 3)


## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
from tensorflow.keras import layers

model = tf.keras.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
from tensorflow.python.keras.layers import Input, Dense
# input layer 
model.add(Dense(12, activation='relu', input_shape=(4,)))

# hidden layer 
model.add(Dense(12, activation='relu'))

# output layer 
model.add(Dense(3, activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
model.compile(loss='categorical_crossentropy',
              optimizer='SGD',
              metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 12)                60        
_________________________________________________________________
dense_1 (Dense)              (None, 12)                156       
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 39        
Total params: 255
Trainable params: 255
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.layers
model.trainable_variables

[<tf.Variable 'dense/kernel:0' shape=(4, 12) dtype=float32, numpy=
 array([[ 0.20154661, -0.07225162, -0.18018141, -0.04349983, -0.571147  ,
          0.2261765 ,  0.29408258,  0.45614952, -0.3351804 , -0.33901322,
         -0.23222622,  0.27230465],
        [-0.44925213,  0.05886596,  0.09137678,  0.48951036, -0.60078186,
          0.02600217,  0.1647827 , -0.36824614,  0.28098398,  0.05613559,
         -0.48063213,  0.21641988],
        [ 0.19629759, -0.19969416,  0.12421077, -0.3544096 ,  0.4320131 ,
         -0.07272321,  0.54933184, -0.32146376,  0.38186687,  0.03225905,
         -0.00697124, -0.34767023],
        [ 0.42341846,  0.4554631 , -0.23467803,  0.228787  , -0.3213236 ,
          0.34503853,  0.5721254 , -0.5282305 ,  0.3658796 ,  0.19631088,
          0.10673809, -0.41075867]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(12,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(12, 

## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [15]:
# Train neural network
model.fit(X_train, y_train_binary,epochs=100, verbose=1, batch_size=1,   validation_data=(X_test, y_test_binary))


Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 0s 4ms/sample - loss: 0.8710 - accuracy: 0.5714 - val_loss: 0.5794 - val_accuracy: 0.7105
Epoch 2/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.5662 - accuracy: 0.7143 - val_loss: 0.4570 - val_accuracy: 0.7105
Epoch 3/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.4688 - accuracy: 0.7679 - val_loss: 0.4122 - val_accuracy: 0.7105
Epoch 4/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.4089 - accuracy: 0.8125 - val_loss: 0.2888 - val_accuracy: 1.0000
Epoch 5/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.3295 - accuracy: 0.8482 - val_loss: 0.3640 - val_accuracy: 0.7368
Epoch 6/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.3333 - accuracy: 0.8571 - val_loss: 0.2008 - val_accuracy: 1.0000
Epoch 7/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.3156 -

## Question 10

### Make predictions
- Predict labels on one row

In [16]:
score=model.evaluate(X_test, y_test_binary)
score

38/38 [==============================] - 0s 2ms/sample - loss: 0.0491 - accuracy: 0.9737


[0.04908430370453157, 0.9736842]

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [17]:
y_predict = model.predict(X_test)
y_predict


array([[3.28866066e-04, 9.79287505e-01, 2.03836970e-02],
       [9.99836564e-01, 1.63463468e-04, 2.66305443e-15],
       [8.15293077e-09, 1.23436691e-03, 9.98765707e-01],
       [2.54150713e-04, 9.70190406e-01, 2.95554549e-02],
       [1.77172929e-04, 9.89456356e-01, 1.03664370e-02],
       [9.99579847e-01, 4.20095777e-04, 3.78028568e-14],
       [2.11567013e-03, 9.97750103e-01, 1.34198199e-04],
       [5.11244252e-06, 5.73791154e-02, 9.42615747e-01],
       [1.05465762e-04, 3.45460922e-01, 6.54433548e-01],
       [5.51262347e-04, 9.98980105e-01, 4.68652754e-04],
       [2.33392493e-05, 1.76930889e-01, 8.23045731e-01],
       [9.99230742e-01, 7.69319769e-04, 3.42698905e-13],
       [9.99868870e-01, 1.31150562e-04, 1.38077085e-15],
       [9.99302268e-01, 6.97748095e-04, 2.53852874e-13],
       [9.99819577e-01, 1.80410003e-04, 6.89660451e-15],
       [1.68924962e-04, 9.92118716e-01, 7.71232415e-03],
       [3.29255471e-07, 6.38048397e-03, 9.93619144e-01],
       [7.05630169e-04, 9.97698



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [19]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42)

In [21]:
!pip install pyDrive

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [0]:
# run this cell to upload file if you are using google colab
#As alertnative I am using mount to read from gdrive
# from google.colab import files
# files.upload()

In [43]:
from google.colab import drive
drive.mount('/content/gdrive/')

Drive already mounted at /content/gdrive/; to attempt to forcibly remount, call drive.mount("/content/gdrive/", force_remount=True).


In [0]:
shareprices = pd.read_csv('/content/gdrive/My Drive/ColabNotebook/bangalore-aug19-batch-pavan88/prices.csv')

In [45]:
shareprices.head()

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

In [46]:
shareprices.describe()

open          close            low           high        volume
count  851264.000000  851264.000000  851264.000000  851264.000000  8.512640e+05
mean       70.836986      70.857109      70.118414      71.543476  5.415113e+06
std        83.695876      83.689686      82.877294      84.465504  1.249468e+07
min         0.850000       0.860000       0.830000       0.880000  0.000000e+00
25%        33.840000      33.849998      33.480000      34.189999  1.221500e+06
50%        52.770000      52.799999      52.230000      53.310001  2.476250e+06
75%        79.879997      79.889999      79.110001      80.610001  5.222500e+06
max      1584.439941    1578.130005    1549.939941    1600.930054  8.596434e+08

In [47]:
shareprices.dtypes

date       object
symbol     object
open      float64
close     float64
low       float64
high      float64
volume    float64
dtype: object

In [48]:
shareprices.isna().sum()

date      0
symbol    0
open      0
close     0
low       0
high      0
volume    0
dtype: int64

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [49]:
shareprices.drop(['date','symbol'], axis=1,inplace=True)
shareprices.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [0]:
dfs_1k=shareprices[:1000]

In [51]:
dfs_1k.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
X = dfs_1k.iloc[:,0:4]
y_actual=dfs_1k['volume']

In [53]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
open     1000 non-null float64
close    1000 non-null float64
low      1000 non-null float64
high     1000 non-null float64
dtypes: float64(4)
memory usage: 31.4 KB


In [54]:
y_actual.head()

0    2163600.0
1    2386400.0
2    2489500.0
3    2006300.0
4    1408600.0
Name: volume, dtype: float64

In [0]:
X = dfs_1k.drop(['volume'], axis = 1) # this will internally select open, close, low & high features.
y_actual=(y_actual/1000000)

In [56]:
X

open       close         low        high
0    123.430000  125.839996  122.309998  126.250000
1    125.239998  119.980003  119.940002  125.540001
2    116.379997  114.949997  114.930000  119.739998
3    115.480003  116.620003  113.500000  117.440002
4    117.010002  114.970001  114.089996  117.330002
..          ...         ...         ...         ...
995   63.310001   63.590000   63.240002   63.639999
996   27.160000   26.990000   26.680000   27.299999
997   28.320000   28.770000   28.010000   28.809999
998   44.000000   44.799999   43.750000   44.810001
999   36.080002   37.139999   36.009998   37.230000

[1000 rows x 4 columns]

In [57]:
y_actual

0       2.1636
1       2.3864
2       2.4895
3       2.0063
4       1.4086
        ...   
995     2.1332
996     1.9824
997    37.1528
998     6.5686
999     5.6043
Name: volume, Length: 1000, dtype: float64

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
X = X.to_numpy(dtype='float32')
y = y_actual.to_numpy(dtype='float32')

In [59]:
print(X.shape)
print(y.shape)

(1000, 4)
(1000,)


## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [60]:
X_norm_tensor = tf.math.l2_normalize(X)
X_norm_tensor

<tf.Tensor: shape=(1000, 4), dtype=float32, numpy=
array([[0.02202894, 0.02245906, 0.02182905, 0.02253223],
       [0.02235197, 0.02141321, 0.02140607, 0.02240551],
       [0.0207707 , 0.02051548, 0.02051192, 0.02137037],
       ...,
       [0.00505436, 0.00513467, 0.00499903, 0.00514181],
       [0.00785282, 0.0079956 , 0.0078082 , 0.00799738],
       [0.00643931, 0.00662849, 0.00642682, 0.00664455]], dtype=float32)>

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
W = tf.Variable(tf.zeros(shape=[4,1]), name="Weights")
b = tf.Variable(tf.zeros(shape=[1]), name="Bias")

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
@tf.function 
def get_prediction(X, W, b):     
    y_pred = tf.add(tf.matmul(X,W),b,name='output')     
    return y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
@tf.function 
def loss(y, y_pred):     
#     diff = y_actual - y_pred     
#     sqr = tf.square(diff)     
#     avg = tf.reduce_mean(sqr) 
    loss = tf.reduce_mean(tf.square(y-y_pred),name='Loss')
    return loss 

In [0]:
# Mean Squared Error Cost Function
y_pred = tf.add(tf.matmul(X_norm_tensor, W), b)
cost = tf.losses.mean_squared_error(y_actual, y_pred)

In [65]:
cost

<tf.Tensor: shape=(1000,), dtype=float32, numpy=
array([237.28671, 237.28671, 237.28671, 237.28671, 237.28671, 237.28671,
       237.28671, 237.28671, 237.28671, 237.28671, 237.28671, 237.28671,
       237.28671, 237.28671, 237.28671, 237.28671, 237.28671, 237.28671,
       237.28671, 237.28671, 237.28671, 237.28671, 237.28671, 237.28671,
       237.28671, 237.28671, 237.28671, 237.28671, 237.28671, 237.28671,
       237.28671, 237.28671, 237.28671, 237.28671, 237.28671, 237.28671,
       237.28671, 237.28671, 237.28671, 237.28671, 237.28671, 237.28671,
       237.28671, 237.28671, 237.28671, 237.28671, 237.28671, 237.28671,
       237.28671, 237.28671, 237.28671, 237.28671, 237.28671, 237.28671,
       237.28671, 237.28671, 237.28671, 237.28671, 237.28671, 237.28671,
       237.28671, 237.28671, 237.28671, 237.28671, 237.28671, 237.28671,
       237.28671, 237.28671, 237.28671, 237.28671, 237.28671, 237.28671,
       237.28671, 237.28671, 237.28671, 237.28671, 237.28671, 237.28671,
  

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(x, y, w, b, learning_rate=0.01):          
    # Record mathematical operations on 'tape' to calculate loss     
    with tf.GradientTape() as t:         
        t.watch([w,b])         
        current_prediction = get_prediction(x, w, b)         
        current_loss = loss(y, current_prediction)          
        # Calculate Gradients for Loss with respect to Weights and Bias     
    dw, db = t.gradient(current_loss,[w, b])          
    # Update Weights and Bias     
    w = w - learning_rate * dw     
    b = b - learning_rate * db          
    return w, b 

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [67]:
for i in range(100):         
    W, b = train(X_norm_tensor, y, W, b, learning_rate=0.01)     
    pred = get_prediction(X_norm_tensor, W, b)
    print('Current Training Loss on iteration', i, loss(y, pred))

Current Training Loss on iteration 0 tf.Tensor(236.16759, shape=(), dtype=float32)
Current Training Loss on iteration 1 tf.Tensor(235.09299, shape=(), dtype=float32)
Current Training Loss on iteration 2 tf.Tensor(234.06102, shape=(), dtype=float32)
Current Training Loss on iteration 3 tf.Tensor(233.06998, shape=(), dtype=float32)
Current Training Loss on iteration 4 tf.Tensor(232.11781, shape=(), dtype=float32)
Current Training Loss on iteration 5 tf.Tensor(231.20381, shape=(), dtype=float32)
Current Training Loss on iteration 6 tf.Tensor(230.32585, shape=(), dtype=float32)
Current Training Loss on iteration 7 tf.Tensor(229.48265, shape=(), dtype=float32)
Current Training Loss on iteration 8 tf.Tensor(228.67297, shape=(), dtype=float32)
Current Training Loss on iteration 9 tf.Tensor(227.89539, shape=(), dtype=float32)
Current Training Loss on iteration 10 tf.Tensor(227.14832, shape=(), dtype=float32)
Current Training Loss on iteration 11 tf.Tensor(226.43114, shape=(), dtype=float32)
Cu

### Observe values of Weight
- Print the updated values

In [68]:
print(f'W : {W.numpy()}')

W : [[0.0547828 ]
 [0.05488191]
 [0.05422735]
 [0.05533117]]


### Observe values of Bias
- Print the updated values

In [69]:
print(f'b  = {b.numpy()} ')

b  = [4.607657] 
